version: "3.8"
services:
  db:
    image: postgres:16-alpine # 가볍고 안정적인 버전
    container_name: voda_postgres_local
    restart: always
    environment:
      POSTGRES_USER: voda_user
      POSTGRES_PASSWORD: voda_password
      POSTGRES_DB: voda_db
    ports:
      - "5435:5432" # 내 컴퓨터의 5435 포트와 연결
    volumes:
      - voda_postgres_data:/var/lib/postgresql/data # Docker named volume 사용

volumes:
  voda_postgres_data:

services:
  voda-api:
    image: ${DOCKER_USERNAME}/voda-api:develop
    container_name: voda-api-server
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    network_mode: "bridge" # 💡 기존 Redis와 통신하기 위해